### ISSUE TITLE
Remove generated JS files

### ISSUE THREAD

**Issue by drobakowski** [synlay/elm-state-button#3]
As this is primary a elm library, I think we should stick to elm sources only and let the client library decide on how to integrate this in his project. Rather than including the generated JS sources ourself, we could let travis build these files and create releases on GitHub with these build artifacts. See for example https://github.com/erlang/rebar3/releases. As long as there is no really a need or demand for it I would keep this repository as minimal as possible for now and remove all generated JS files.

**Comment by ghost** [comment]
Fixed 39d7d599944c3491ca9b9e1622a0668e6538983f
